server:
  post: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      sever:
        git:
          uri: https://github.com/shabbirdwd53/config-server
            clone-on-start: true